## LOAD DATASET

In [3]:
import pandas as pd

# Load CSV file
clinical= pd.read_csv("clinical_trials_raw_patient2trial_conditions.csv")

## OBSERVING THE DATASET

In [4]:
clinical.shape

(60337, 16)

In [5]:
clinical.columns

Index(['source_condition_query', 'nct_id', 'title', 'official_title',
       'brief_summary', 'conditions', 'interventions', 'overall_status',
       'study_type', 'phase', 'sex', 'minimum_age', 'maximum_age',
       'healthy_volunteers', 'eligibility_criteria', 'clinicaltrials_url'],
      dtype='str')

In [6]:
clinical.head()

,source_condition_query,nct_id,title,official_title,brief_summary,conditions,interventions,overall_status,study_type,phase,sex,minimum_age,maximum_age,healthy_volunteers,eligibility_criteria,clinicaltrials_url
0,breast cancer,NCT03676114,Effect of Perioperative Low Dose Ketamine on P...,Effect of Perioperative Low Dose Ketamine on P...,Breast cancer patients often have perioperativ...,Breast Cancer,ketamine | Normal saline,UNKNOWN,INTERVENTIONAL,PHASE4,FEMALE,20 Years,65 Years,False,Inclusion Criteria:\n\n1. American Society of ...,https://clinicaltrials.gov/study/NCT03676114
1,breast cancer,NCT02941614,Implementing Systematic Distress Screening in ...,Implementing Systematic Distress Screening in ...,Many breast cancer patients experience psychol...,Breast Cancer,Distress screening,COMPLETED,OBSERVATIONAL,NaN,ALL,18 Years,NaN,False,Inclusion Criteria:\n\n* Newly diagnosed with ...,https://clinicaltrials.gov/study/NCT02941614
2,breast cancer,NCT04509063,Investigating Public Enthusiasm for Mammograph...,Investigating Public Enthusiasm for Mammograph...,"Based on an American study by Scherer et al., ...",Breast Neoplasm Female | Mammography Screening...,Information about hypothetical mammography scr...,COMPLETED,INTERVENTIONAL,NaN,FEMALE,44 Years,49 Years,True,Inclusion Criteria:\n\n* Residence: Central De...,https://clinicaltrials.gov/study/NCT04509063
3,breast cancer,NCT04327063,MIRs 04 : Interpectoral Nerve Block With Ropiv...,A Double-blind Randomized Trial of Interpector...,Compare the effect of ropivacaine versus place...,Malignant Neoplasm of Breast,Saline | Ropivacaine,COMPLETED,INTERVENTIONAL,PHASE3,FEMALE,18 Years,85 Years,False,Inclusion Criteria:\n\n1. Women with non-metas...,https://clinicaltrials.gov/study/NCT04327063
4,breast cancer,NCT06778863,A Study of CLSP-1025 in Adult Patients With So...,GUARDIAN-101: A Phase 1 Dose Escalation and Ex...,Phase 1 dose escalation and expansion study of...,Advanced Solid Tumor | Unresectable Solid Tumo...,CLSP-1025,RECRUITING,INTERVENTIONAL,PHASE1,ALL,18 Years,NaN,False,Key Inclusion Criteria:\n\n* Patients must be ...,https://clinicaltrials.gov/study/NCT06778863

## FOCUS ON RELEVANT COLUMNS

In [7]:
# Keep only the important columns
clinical = clinical[
    [
        "brief_summary",
        "source_condition_query",
        "conditions",
        "minimum_age",
        "maximum_age",
    ]
]

# Drop rows with missing values in key columns
clinical = clinical.dropna(subset=['brief_summary', 'source_condition_query'])

## TEXT CLEANING

In [8]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = re.sub(r'[^a-zA-Z]', ' ', text.lower())   # remove non-letters
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(w) for w in tokens if w not in stop_words]
    return " ".join(tokens)

clinical['clean_summary'] = clinical['brief_summary'].apply(clean_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nivit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nivit\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [9]:
clinical.head()

,brief_summary,source_condition_query,conditions,minimum_age,maximum_age,clean_summary
0,Breast cancer patients often have perioperativ...,breast cancer,Breast Cancer,20 Years,65 Years,breast cancer patient often perioperative emot...
1,Many breast cancer patients experience psychol...,breast cancer,Breast Cancer,18 Years,NaN,many breast cancer patient experience psycholo...
2,"Based on an American study by Scherer et al., ...",breast cancer,Breast Neoplasm Female | Mammography Screening...,44 Years,49 Years,based american study scherer et al hypothesize...
3,Compare the effect of ropivacaine versus place...,breast cancer,Malignant Neoplasm of Breast,18 Years,85 Years,compare effect ropivacaine versus placebo pect...
4,Phase 1 dose escalation and expansion study of...,breast cancer,Advanced Solid Tumor | Unresectable Solid Tumo...,18 Years,NaN,phase dose escalation expansion study clsp fir...

## SAVE THE CLEANED DATA

In [10]:
clinical.to_csv("clinical_cleaned.csv", index=False)